# CONFIG_CC3200SDK_BUILTIN can be used for debugging purposes.
# In that case, the CC3200 SDK driverlib must be built with level 0
# optimization (-O0) for the uart module to work properly.
# Note the default build for Zephyr is CONFIG_CC3200SDK_ROM_DRIVERLIB=y
# which uses the ROM versions of the APIs instead.
ccflags-$(CONFIG_CC3200SDK_BUILTIN) += -O0
ccflags-$(CONFIG_HAS_CC3200SDK) += -D$(COMPILER)
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/gpio.o
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/interrupt.o
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/pin.o
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/uart.o
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/udma.o
# spi.c warns on parens
CFLAGS_spi.o += -Wno-parentheses
obj-$(CONFIG_CC3200SDK_BUILTIN) += driverlib/spi.o
# Need prcm and utils for PRCMCC3200MCUInit which is not in ROM
obj-$(CONFIG_HAS_CC3200SDK) += driverlib/utils.o
obj-$(CONFIG_HAS_CC3200SDK) += driverlib/prcm.o

obj-$(CONFIG_CC3200SDK_SIMPLELINK) += driverlib/timer.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/device.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/driver.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/flowcont.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/fs.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/netapp.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/netcfg.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/nonos.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/socket.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/spawn.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/source/wlan.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/cc_pal.o
obj-$(CONFIG_CC3200SDK_SIMPLELINK) += simplelink/cb_weak.o
